apiVersion: v1
kind: Service
metadata:
  name: sensor-even
  labels:
    lecture: "03"
    exercise: powergrid-sampler
    component: sensor
    course: bigdata
    app: sensor-even
spec:
  selector:
    app: sensor-even
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
