FROM python:3

# Set environment variables to prevent Python from writing .pyc files to disk and buffering stdout and stderr
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install dependencies needed for building Python packages
# RUN apk add --no-cache build-base libffi-dev

# Create and set the working directory
WORKDIR /

# Copy the requirements.txt file to the working directory
COPY requirements.txt .

# Install dependencies from requirements.txt and then remove the file
RUN pip install --no-cache-dir -r requirements.txt && rm requirements.txt

# Add user to run the application
RUN adduser sensor

# Make folder for application data
RUN mkdir powergrid && chown sensor:sensor powergrid

# Change to the non-root user
USER sensor

# Copy the rest of the application code to the working directory
COPY *.py ./


# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run gunicorn when the container launches
CMD ["gunicorn", "-b", ":5000", "app:app"]
