apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sensor-odd
  labels:
    lecture: "02"
    exercise: powergrid-sampler
    component: sensor
    course: bigdata
    app: sensor-odd
    group: odd
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      lecture: "02"
      exercise: powergrid-sampler
      component: sensor
      course: bigdata
      app: sensor-odd
      group: odd
  template:
    metadata:
      labels:
        lecture: "02"
        exercise: powergrid-sampler
        component: sensor
        course: bigdata
        app: sensor-odd
        group: odd
    spec:
      containers:
        - name: sensor-odd
          image: ghcr.io/the0mikkel/bigdatacourseexercises:02-sensor
          resources:
            requests:
              cpu: "20m"
              memory: "55M"
            limits:
              cpu: "100m"
              memory: "100M"
          livenessProbe:
            httpGet:
              path: /_status/healthz
              port: 5000
            initialDelaySeconds: 90
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /_status/healthz
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 10
          env:
            - name: SENSORS
              value: "5,15,25,35,45,55,65,75,85,95"
          ports:
            - containerPort: 5000
              name: http
