apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader
  labels:
    lecture: "02"
    exercise: powergrid-sampler
    component: reader
    course: bigdata
    app: reader
    group: reader
spec:
  replicas: 1
  selector:
    matchLabels:
      lecture: "02"
      exercise: powergrid-sampler
      component: reader
      course: bigdata
      app: reader
      group: reader
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        lecture: "02"
        exercise: powergrid-sampler
        component: reader
        course: bigdata
        app: reader
        group: reader
    spec:
      containers:
        - name: reader
          image: ghcr.io/the0mikkel/bigdatacourseexercises:02-sensor
          resources:
            requests:
              cpu: "100m"
              memory: "55M"
            limits:
              cpu: "1200m"
              memory: "500M"
          livenessProbe:
            httpGet:
              path: /_status/healthz
              port: 5000
            initialDelaySeconds: 90
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /_status/healthz
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 10
          env:
            - name: READER
              value: "true"
          ports:
            - containerPort: 5000
              name: http
          imagePullPolicy: Always
