apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hive-warehouse-pvc
  labels:
    app: hiveserver2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiveserver2
  labels:
    app: hiveserver2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hiveserver2
  template:
    metadata:
      labels:
        app: hiveserver2
    spec:
      containers:
        - name: hiveserver2
          image: apache/hive:3.1.3
          env:
            - name: SERVICE_NAME
              value: hiveserver2
            - name: SERVICE_OPTS
              value: "-Dhive.metastore.uris=thrift://hive-metastore:9083"
            - name: IS_RESUME
              value: "true"
          ports:
            - containerPort: 10000
              name: thrift
            - containerPort: 10002
              name: http
          volumeMounts:
            - name: hive-warehouse
              mountPath: /opt/hive/data/warehouse
      volumes:
        - name: hive-warehouse
          persistentVolumeClaim:
            claimName: hive-warehouse-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: hiveserver2
  labels:
    app: hiveserver2
spec:
  ports:
    - name: thrift
      port: 10000
      targetPort: 10000
      protocol: TCP
    - name: http
      port: 10002
      targetPort: 10002
      protocol: TCP
  selector:
    app: hiveserver2
