apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "password"
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "password"
  ME_CONFIG_BASICAUTH: "false"
  ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
  ME_CONFIG_MONGODB_ADMINPASSWORD: "password"
  ME_CONFIG_MONGODB_URL: "mongodb://admin:password@mongodb:27017"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "mongodb-pvc"
  labels:
    app: "mongodb"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "mongodb"
spec:
  type: "NodePort"
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: "mongodb"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "mongodb"
spec:
  selector:
    matchLabels:
      app: "mongodb"
  replicas: 1
  template:
    metadata:
      labels:
        app: "mongodb"
    spec:
      containers:
        - name: "mongodb"
          image: "mongo"
          imagePullPolicy: "Always"
          envFrom:
            - configMapRef:
                name: mongodb-config
          ports:
            - containerPort: 27017
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "mongo-express"
spec:
  type: "NodePort"
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: "mongo-express"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "mongo-express"
spec:
  selector:
    matchLabels:
      app: "mongo-express"
  replicas: 1
  template:
    metadata:
      labels:
        app: "mongo-express"
    spec:
      containers:
        - name: "mongo-express"
          image: "mongo-express"
          imagePullPolicy: "Always"
          envFrom:
            - configMapRef:
                name: mongodb-config
          ports:
            - containerPort: 8081
