name: Docker push for exercise 02 - Powergrid Sampler

on:
  push:
    branches:
      - main
    paths:
      - 'lectures/02/powergrid-sampler/**'

jobs:
  docker-push:
    name: Docker push for exercise 02 - Powergrid Sampler
    uses: the0mikkel/ci/.github/workflows/docker.yml@v1.1.4
    with:
      dockerfile: 'lectures/02/powergrid-sampler/docker/dockerfile'
      context: 'lectures/02/powergrid-sampler'
      tags: |
          type=raw,value=02-sensor
